import type { MathSymbol } from './math';

const symbol = (
  id: string,
  glyph: string,
  name: string,
  category: string,
  template = id,
  keywords = '',
  wrap = false,
): MathSymbol => ({ id, glyph, name, category, template, keywords, wrap });

export const CATEGORIES = [
  'All',
  'Greek',
  'Operators',
  'Relations',
  'Sets',
  'Calculus',
  'Structures',
];
export const SYMBOLS: MathSymbol[] = [
  symbol('alpha', 'α', 'Alpha', 'Greek'),
  symbol('beta', 'β', 'Beta', 'Greek'),
  symbol('gamma', 'γ', 'Gamma', 'Greek'),
  symbol('delta', 'δ', 'Delta', 'Greek'),
  symbol('epsilon', 'ε', 'Epsilon', 'Greek'),
  symbol('theta', 'θ', 'Theta', 'Greek'),
  symbol('lambda', 'λ', 'Lambda', 'Greek'),
  symbol('mu', 'μ', 'Mu', 'Greek'),
  symbol('pi', 'π', 'Pi', 'Greek'),
  symbol('rho', 'ρ', 'Rho', 'Greek'),
  symbol('sigma', 'σ', 'Sigma', 'Greek'),
  symbol('phi', 'φ', 'Phi', 'Greek'),
  symbol('psi', 'ψ', 'Psi', 'Greek'),
  symbol('omega', 'ω', 'Omega', 'Greek'),
  symbol('Delta', 'Δ', 'Capital delta', 'Greek'),
  symbol('Omega', 'Ω', 'Capital omega', 'Greek'),
  symbol('plusminus', '±', 'Plus or minus', 'Operators', '+-'),
  symbol('times', '×', 'Multiply', 'Operators', 'times', 'product multiplication'),
  symbol('dot', '⋅', 'Dot product', 'Operators'),
  symbol('div', '÷', 'Divide', 'Operators'),
  symbol('infinity', '∞', 'Infinity', 'Operators', 'oo'),
  symbol('factorial', 'n!', 'Factorial', 'Operators', '{{n}}!'),
  symbol('less-equal', '≤', 'Less than or equal', 'Relations', '<='),
  symbol('greater-equal', '≥', 'Greater than or equal', 'Relations', '>='),
  symbol('not-equal', '≠', 'Not equal', 'Relations', '!='),
  symbol('approx', '≈', 'Approximately equal', 'Relations', 'approx'),
  symbol('equiv', '≡', 'Equivalent', 'Relations', 'equiv'),
  symbol('arrow', '→', 'Right arrow', 'Relations', '->'),
  symbol('implies', '⇒', 'Implies', 'Relations', '=>'),
  symbol('iff', '⇔', 'If and only if', 'Relations', '<=>'),
  symbol('in', '∈', 'Element of', 'Sets'),
  symbol('notin', '∉', 'Not an element', 'Sets', 'in.not'),
  symbol('subset', '⊂', 'Subset', 'Sets'),
  symbol('subset-equal', '⊆', 'Subset or equal', 'Sets', 'subset.eq'),
  symbol('union', '∪', 'Union', 'Sets'),
  symbol('inter', '∩', 'Intersection', 'Sets'),
  symbol('emptyset', '∅', 'Empty set', 'Sets', 'nothing'),
  symbol('RR', 'ℝ', 'Real numbers', 'Sets'),
  symbol('NN', 'ℕ', 'Natural numbers', 'Sets'),
  symbol('ZZ', 'ℤ', 'Integers', 'Sets'),
  symbol('CC', 'ℂ', 'Complex numbers', 'Sets'),
  symbol('forall', '∀', 'For all', 'Sets'),
  symbol('exists', '∃', 'There exists', 'Sets'),
  symbol('sum', '∑', 'Summation', 'Calculus', 'sum_(i=1)^n {{i}}', 'sigma series'),
  symbol('product', '∏', 'Product', 'Calculus', 'product_(i=1)^n {{i}}'),
  symbol(
    'integral',
    '∫',
    'Integral',
    'Calculus',
    'integral_a^b {{f(x)}} dif x',
    'integration',
    true,
  ),
  symbol('partial', '∂', 'Partial derivative', 'Calculus'),
  symbol('nabla', '∇', 'Gradient', 'Calculus', 'nabla'),
  symbol('limit', 'lim', 'Limit', 'Calculus', 'lim_(x -> 0) {{f(x)}}'),
  symbol('derivative', 'd/dx', 'Derivative', 'Calculus', 'frac(dif {{f}}, dif x)', '', true),
  symbol('frac', 'a/b', 'Fraction', 'Structures', 'frac({{a}}, b)', 'divide division', true),
  symbol('sqrt', '√', 'Square root', 'Structures', 'sqrt({{x}})', 'radical', true),
  symbol('root', 'ⁿ√', 'Nth root', 'Structures', 'root(3, {{x}})', 'radical', true),
  symbol('power', 'xⁿ', 'Power', 'Structures', '({{x}})^2', 'superscript exponent', true),
  symbol('subscript', 'xₙ', 'Subscript', 'Structures', '({{x}})_n', '', true),
  symbol('mat', '[▦]', 'Matrix', 'Structures', 'mat({{a}}, b; c, d)'),
  symbol('vec', '(⋮)', 'Vector', 'Structures', 'vec({{a}}, b, c)'),
  symbol('abs', '|x|', 'Absolute value', 'Structures', 'abs({{x}})', '', true),
  symbol('binom', '(ⁿₖ)', 'Binomial', 'Structures', 'binom({{n}}, k)', 'choose'),
  symbol(
    'cases',
    '{',
    'Cases',
    'Structures',
    'cases({{x}} & "if" x >= 0, -x & "if" x < 0)',
    'piecewise',
  ),
];

export const QUICK_SYMBOLS = [
  'frac',
  'sqrt',
  'power',
  'subscript',
  'pi',
  'theta',
  'sum',
  'integral',
  'infinity',
  'mat',
].map((id) => SYMBOLS.find((s) => s.id === id)!);
